name: Check code when push

on:
  push:
    branches:
      - "main"
  jobs:
    check-code:
      name: Check code
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@2
        - run: npm install
        - run: npm ci